### ISSUE TITLE
Add menu bar which will allow users load ROM using file browser

### ISSUE THREAD

**Issue by rafzby** [rafzby/chip8-emulator#5]
It would be be nice to make it possible to load ROMs using file browser.

**Comment by pmarco0** [comment]
I tried to add a menu bar (70eed88), here's the result: https://imgur.com/a/nl8y5
I had to change the software behaviour adding a controller to directly instantiate and terminate a Virtual Machine whenever a new ROM is opened. 
If you are fine with that i can create a PR. :)

**Comment by rafzby** [comment]
@pmarco0 Looks fine to me, you can create a PR :)
